apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: istio-system
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    name: http
  selector:
    app: elasticsearch
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: istio-system
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9200
        volumeMounts:
        - mountPath: /data/elasticsearch
          name: elasticsearch-data
      volumes:
      - name: elasticsearch-data
        emptyDir: {}
